service: oasis-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  region: eu-west-2
  profile: serverless
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  artifact: target/hello-dev.jar

functions:
  locations:
    handler: com.splashpool.Handler
    events:
      - http:
          path: locations
          method: get
          cors: true
      - http:
          path: locations
          method: post
          cors: true
